services:
  mysql:
    image: mysql:8.0
    container_name: base_nutricion
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Segura123
      MYSQL_DATABASE: Gastro_basque
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: